#this task sets up the server by updating packages and installing neccesary packages
- name: Install packages
  apt: update_cache=yes name={{ item }} state=present #install the packages if they don't exist
  with_items:
    - git
    - nginx

- name: Install nodejs
  shell: |
    curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
    apt-get install -y nodejs

- name: Set up environment for yarn
  shell: | 
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

- name: Install yarn
  apt: 
    update_cache=yes
    name=yarn
    state=present

- name: set and generate locale #neccessary for ubuntu to install and update other packages
  shell: |
    export LANGUAGE=en_US.UTF-8
    export LANG=en_US.UTF-8
    export LC_ALL=en_US.UTF-8