- hosts: all #use all hosts ansible knows about
  become: yes
  become_method: sudo
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - server-setup
    - nginx
    - app_setup
    - startup_service