- hosts: all # all hosts ansible knows about #middle-tier #apply the contents of this playbook to all hosts matching the label
  become: yes  
  become_method: sudo
  vars: 
    ansible_python_interpreter: /usr/bin/python3
    repository_url: https://github.com/mirr254/Bright-Events.git
    repository_path: /var/www/bright-events/
  roles:
    - server-setup
    - nginx
    - db-setup
    - app-configuration
    - startup-service



  


        
  